### ISSUE TITLE
Allow setting imagePullSecrets

### ISSUE THREAD

**Issue by nivimorbgp** [apolicy-io/charts#1]
Hi,

Due to docker rate limit, we need to be able to set `imagePullSecrets` for the service accounts.

The necessary changes are:
1. In the values.yaml file, add the following at the end of the file
```
# configure docker registry
imagePullSecrets: []
```

2. In the serviceaccount.yaml, for each service account, add:
```
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
```

**Comment by ido-gold-apolicy** [comment]
Chart now supports settings the imagePullSecrets for service accounts.
e.g. --set imagePullSecrets[0].name="myRegistry"
